
APP:
  ENVIRONMENT: prod
  LOGGER : DEBUG
  # Only accept True or False

INPUT:
  DIR : ~/PycharmProjects/new-america-housing-loss-public/cli/collection/tests/resources

OUTPUT:
  DIR : ~/PycharmProjects/new-america-housing-loss-public/reports