name: DataKind New America Housing Tool CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  cli_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cli-tests
        working-directory: ./cli
        run: |
          make requirements
          make pytest